config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :posts do
    resources :comments
  end
  resources :contacts, only: [:new, :create]

  get '/about', to: 'pages#about'
  get '/dashboard', to: 'pages#dashboard'
  get '/users', to: 'pages#userlist', as: :user_list

  get '/sayhey', to: 'contacts#new'

  get '/sayhey-thanks', to: 'contacts#create'

  get '/announcement', to: 'pages#announcement', as: :announcement

  get 'privacy', to: 'pages#privacy', as: :privacy

  get 'terms', to: 'pages#terms', as: :terms

  devise_scope :user do
    # using login path for registration
    get '/meow', to: 'devise/sessions#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'

  end
  root 'pages#home'
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories
  validates :title, presence: true, length: { minimum: 5}
  validates :body, presence: true
  has_attached_file :image, styles: { large: "600x600>",medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_attached_file :logo, styles: { large: "600x600>",medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include AmazonSignature
  before_action :authenticate_user! , except: [:index, :show]
  def index
    @posts = Post.order('updated_at asc')
    redirect_to "/"
  end
  def new
    @categories_list = Category.all
    @post = Post.new
    @hash = AmazonSignature::data_hash
  end

  def show
    @post = Post.find_by_slug(params[:id])
    @categories_list = @post.categories

    @related_posts = []

    @categories_list.each do |category|
      if category.posts.length > 0
        category.posts.each do |post|
          if (post != @post) && (!@related_posts.include?(post))
            @related_posts << post
          end
        end
      end
    end
  end

  def edit
    @categories = Category.all
    @hash = AmazonSignature::data_hash
    @post = Post.find_by_slug(params[:id])
    @categories_list = @post.categories
  end

  def update
    @post = Post.find_by_slug(params[:id])
    if params[:post][:category_ids] != nil
      @post.categories.each do |category|
          @post.categories.delete(category)
      end
      params[:post][:category_ids].each do |category|
        @post.categories <<  Category.find( category.to_f)
      end
    end
    if params[:post][:created_at].length < 23
      @post.created_at =  DateTime.strptime(params[:post][:created_at] + ' 00:00:00', '%m/%d/%Y %H:%M:%S')
      @post.save
    end
    @post.update(params[:post].permit(:title, :description, :body, :image,:category_ids, :logo, :id))

    if @post.update(params[:post].permit(:title,:description, :body, :image,:category_ids, :logo, :id))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def create
    @hash = AmazonSignature::data_hash
    @post = Post.new(post_params)
    params[:post][:category_ids].each do |category|
      if !@post.categories.include?(Category.find( category.to_f))
        @post.categories <<  Category.find( category.to_f)
      end
    end
    @post.save
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  private
    def post_params
      params.require(:post).permit(:title, :body, :description, :logo, :image,:created_at , :category_ids)
    end
end

app/views/posts/_edit_form.html.erb
<div id="edit-form">
  <%= form_for @post, html: { multipart: true } do |f| %>
    <% if @post.errors.any? %>
      <div class="errors">
        <p><%= pluralize(@post.errors.count, "error")%> prevented this post from saving</p>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg%></li>
          <% end %>
        </ul>
      </div>
    <% end%>
    <div id="post-hero" style="background-image: url('<%= @post.image%>');">
      <div class="hero-text">
        <p><%= f.text_field :description %></p>
        <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
      </div>
    </div>
    <div class="container">
      <p class="created-at">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </p>
      <p class="created-at">
        Created at
        <%= f.text_field :created_at, :class => 'datepicker'%>
      </p>
      <p>
        <%= f.label :body %>
        <%= f.text_area :body %>
      </p>
      <p>
        <%= f.label :image %>
        <%= f.file_field :image, id: 'pictureInput' %>
      </p>
      <p>
        <%= f.label :logo %>
        <%= f.file_field :logo %>
      </p>
      <p>Categories</p>

      <% Category.all.each do |category| %>
      <div class="category-checkbox">
        <input type="checkbox" name="post[category_ids][]" <%= "checked" if @post.categories.include?(category)%> value="<%=category.id%>">
        <label>
          <%= category.name %>
        </label>
      </div>

      <% end %>
      <p>
        <%= f.submit %>
      </p>
    </div>
  <% end %>
</div>

<!-- Initialize the editor. -->
<script>
  $(function() {
    $('#post_body').froalaEditor({
      key: 'kA1atA6kfg==',
      imageUploadMethod: 'POST',
      imageUploadToS3: {
        bucket: '<%= @hash[:bucket] %>',
        region: 's3', // Change the region if it is different
        keyStart: '<%= @hash[:key_start] %>',
        callback: function (url, key) {
          console.log (url);
          console.log (key);
        },
        params: {
          acl: '<%= @hash[:acl] %>',
          AWSAccessKeyId: '<%= @hash[:access_key] %>',
          policy: '<%= @hash[:policy] %>',
          signature: '<%= @hash[:signature] %>',
        }
      }
    });
  });
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });

</script>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f|%>
  <% if @post.errors.any?%>
    <div class="errors">
      <p><%= pluralize(@post.errors.count, "error")%> prevented this post from saving</p>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg%></li>
        <% end %>
      </ul>
    </div>
  <% end%>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    Created at
    <%= f.text_field :created_at, :class => 'datepicker'%>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.file_field :image, id: 'pictureInput' %>
  </p>
  <p>Categories</p>

  <% Category.all.each do |category| %>
  <div class="category-checkbox">
    <input type="checkbox" name="post[category_ids][]" <%= "checked" if @post.categories.include?(category)%> value="<%=category.id%>">
    <label>
      <%= category.name %>
    </label>
  </div>

  <% end %>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<!-- Initialize the editor. -->
<script>
$( document ).ready(function() {
    $('#post_body').froalaEditor({
      key: 'kA1atA6kfg==',
      imageUploadMethod: 'POST',
      imageUploadToS3: {
        bucket: '<%= @hash[:bucket] %>',
        region: 's3', // Change the region if it is different
        keyStart: '<%= @hash[:key_start] %>',
        callback: function (url, key) {
          console.log (url);
          console.log (key);
        },
        params: {
          acl: '<%= @hash[:acl] %>',
          AWSAccessKeyId: '<%= @hash[:access_key] %>',
          policy: '<%= @hash[:policy] %>',
          signature: '<%= @hash[:signature] %>',
        }
      }
    });
    $('.datepicker').datepicker();
  });
</script>

app/views/posts/edit.html.erb
<div class="projects-form">
  <%= render "edit_form" %>
</div>

app/views/posts/index.html.erb
<div id="posts-list">
  <div class="row no-margin">
    <% @posts.each_with_index do |post, index|%>
      <a href="/posts/<%= post.slug%>">
        <div class="col-sm-6 col-md-4 ">
          <div class="post" style="background-image: url('<%= image_path(post.image)%>');">
            <div class="post-content">
              <p><%= post.title %></p>
              <p class="date"><%= post.created_at.to_date.to_formatted_s(:long_ordinal)  %></p>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="projects-form">
  <div class="container">
    <%= render "form" %>
  </div>
</div>

app/views/posts/show.html.erb
<div id="post-hero" style="background-image: url('<%= image_path(@post.image)%>');">
  <div class="hero-text">
    <p><%= @post.description %></p>
    <% if user_signed_in? %>
      <%= link_to "Edit", edit_post_path(@post) %>
    <% end %>
  </div>
</div>

<div class="white-bg">
  <div class="container area-padding">
    <div class="row">
      <div class="col-xs-12">
        <p><%= simple_format(@post.body.html_safe,{}, sanitize: false) %></p>
      </div>
    </div>
  </div>
</div>

<div class="project-footer area-padding no-padding-top white-bg">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <p><strong>Posted at:</strong> <%= @post.created_at.to_date.to_formatted_s(:long_ordinal)  %></p>
      </div>
      <div class="col-sm-4">
        <p><strong>STUFF:</strong>
          <% if @categories_list != nil %>
            <% @categories_list.each do |category|%>
              <a href="<%= category_path(category) %>"> <%= category.name %></a>
            <% end %>
          <% end %>
        </p>
      </div>
      <div class="col-sm-4">
        <div class="social-share">
          <i class="fa fa-facebook fb_share"></i>
          <a href="https://twitter.com/intent/tweet/?text=Checkout%20<%=@post.title%>,%20a%20post%20by%20@kaitlynhova%20!%20www.leftbrain.kaitlynhova.com/posts/<%=@post.slug%>"><i class="fa fa-twitter twitter_share"></i>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="posts-list">
  <div class="row no-margin">
    <% @related_posts.first(4).each_with_index do |post, index|%>
      <a href="/posts/<%= post.slug%>">
        <div class="col-sm-6 col-md-4 <%= " hidden-md hidden-lg" if index == 3 %>">
          <div class="post" style="background-image: url('<%= image_path(post.image)%>');">
            <div class="post-content">
              <p><%= post.title %></p>
              <p class="date"><%= post.created_at.to_date.to_formatted_s(:long_ordinal)  %></p>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>
<script>
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

   (function(d, debug){var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];if   (d.getElementById(id)) {return;}js = d.createElement('script'); js.id = id; js.async = true;js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";ref.parentNode.insertBefore(js, ref);}(document, /*debug*/ false));

    function postToFeed(title, desc, url, image) {
        var obj = {method: 'feed',link: url, picture: image,name: title,description: desc};
        function callback(response) {}
        FB.ui(obj, callback);
    }
    var fbShareBtn = document.querySelector('.fb_share');
    fbShareBtn.addEventListener('click', function(e) {
        e.preventDefault();
        var title = "<%= @post.title %>",
            desc = "Enable Community Foundation",
            url = "www.kaitlynhova.com",
            image = "<%= asset_url(@post.image.url)%>";
        postToFeed(title, desc, url, image);

        return false;
    });
</script>