config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :posts do
    resources :comments
  end
  resources :contacts, only: [:new, :create]

  get '/about', to: 'pages#about'
  get '/dashboard', to: 'pages#dashboard'
  get '/users', to: 'pages#userlist', as: :user_list

  get '/sayhey', to: 'contacts#new'

  get '/sayhey-thanks', to: 'contacts#create'

  get '/announcement', to: 'pages#announcement', as: :announcement

  get 'privacy', to: 'pages#privacy', as: :privacy

  get 'terms', to: 'pages#terms', as: :terms

  devise_scope :user do
    # using login path for registration
    get '/meow', to: 'devise/sessions#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'

  end
  root 'pages#home'
end

app/views/layouts/_banner.html.erb
<div class="banner-alert">
  <p>Our organization is changing: <a href="<%= announcement_path%>">Read More</a> </p>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-xs-12">
        <ul class="social">
          <a class="facebook" href="https://www.facebook.com/ECF2015" target="_blank">
            <li>
            </li>
          </a>
          <a class="twitter" href="https://twitter.com/enablehands_ecf" target="_blank">
            <li>
            </li>
          </a>
          <a class="instagram" href="https://www.instagram.com/enablecommunityfoundation/" target="_blank">
            <li>
            </li>
          </a>
          <a class="googleplus" href="https://plus.google.com/100437930616464688963" target="_blank">
            <li>
            </li>
          </a>
          <a class="youtube" href="https://www.youtube.com/channel/UCKdiWmb6xNpK4d7MANT3Ghw/videos" target="_blank">
            <li>
            </li>
          </a>
        </ul>
      </div>
      <div class="col-sm-4 col-xs-12">
        <ul class="links">
          <a href="<%= terms_path%>">
            <li>Terms of Use</li>
          </a>
          <a href="<%= privacy_path%>">
            <li>Privacy</li>
          </a>
        </ul>
      </div>
    </div>
    <p class="legal-infos">ECF is a tax exempt 501 (c)(3) non profit organization. 990s and audited 2015 and 2016 financials are available upon request. <span class="right-text">EIN 47-2170014</span></p>
  </div>
  <div class="footer-logo">
    <img class="logo" src="<%= asset_path('logo.svg')%>">
    <p class="legal-infos centered">© 2017 ECF</p>
  </div>

</footer>

app/views/layouts/_message.html.erb
<% flash.each do |name, message|%>
  <%= content_tag(:div, message, class: "alert")%>
<% end%>

app/views/layouts/_nav.html.erb
<% if user_signed_in?%>
  <div id="admin-bar">
    <div class="container">
      <ul>
        <li>
          <%= link_to :user_list do %>
          <i class="fa fa-users" data-toggle="tooltip" title="Users" data-placement="bottom"></i>
          <% end %>
        </li>
        <li>
          <%= link_to posts_path do %>
          <i class="fa fa-list"  data-toggle="tooltip" title="List" data-placement="bottom"></i>
          <% end %>
        </li>
        <li>
          <%= link_to new_post_path do %>
          <i class="fa fa-plus" data-toggle="tooltip" title="New Post" data-placement="bottom"></i>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path do %>
          <i class="fa fa-power-off" data-toggle="tooltip" title="Log out" data-placement="bottom"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
<% end%>

app/views/layouts/_topnav.html.erb
<div id="top-nav">
  <a href="<%= root_path%>">
    <img src="<%=asset_path('logo.svg') %>">
  </a>
  <ul>
    <a href="<%= root_path + '#mission' %>">
      <li>Mission |</li>
    </a>
    <a href="<%= root_path + '#limbforge'%>">
      <li>LimbForge |</li>
    </a>
    <a href="<%= root_path + '#contact' %>">
      <li>Contact</li>
    </a>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ECF</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Enable Community Foundation" />
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <%= csrf_meta_tags %>
  <!-- GOOGLE ANALYTICS -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-63741704-1', 'auto');
      ga('send', 'pageview');

    </script>
    <link rel="icon" type="image/png" href="<%= asset_path("favicon.png")%>" />
</head>
  <body class="<%= controller.controller_name %>">
    <main>
      <%= render  "layouts/topnav" %>
      <%= render "layouts/message"%>
      <%= yield %>
      <%= render  "layouts/footer" %>
    </main>
    <%= render  "layouts/nav" %>
  </body>
</html>